---
image: base/archlinux

stages:
    - syntax

syntax:
    stage: syntax
    tags:
        - runner
    script:
        - "uname -a"
        - whoami
        - pwd
        # Remove leaseweb mirrors (speed issue)
        - sed -i '/leaseweb/d' /etc/pacman.d/mirrorlist
        - pacman -Sy perl-lwp-protocol-https --noconfirm
        - perl -c check_clever_tanken
